### PR TITLE
Added: Multiply endpoint

### PR DESCRIPTION
**Pull request by onelikeandidie**

### CODE REVIEW

**Comment by onelikeandidie** [comment]
Sorry boss, I make tests quic

**Comment by onelikeandidie** [comment]
Added tests @Unisergius, plz accept

**Comment by PedroCavalheiro** [comment]
📣📣📣 Listen up, folks! 📣📣📣

🚫🧪🚫 Insufficient Test Coverage Detected! 🚫🧪🚫

🚨🚨🚨 Attention, Attention! 🚨🚨🚨

Hold on to your hats, because we're diving into the heart of this pull request like never before! While we absolutely appreciate the inclusion of a test case for the multiplyTwoNumbers function, it's just not enough to satisfy our insatiable hunger for robust test coverage! We're talking about multiplying two numbers here, folks! This is prime territory for testing a plethora of scenarios:

1️⃣ Test for Zero Multiplication: What happens when one of the numbers is zero? Or both?
2️⃣ Test for Negative Multiplication: Can our function handle negative numbers like a boss?
3️⃣ Edge Cases Galore: Let's throw some large numbers, small numbers, and everything in between at this function to see if it breaks a sweat!
4️⃣ Error Handling: What if we pass in non-numeric values? Can our function gracefully handle the unexpected?

🛑🛑🛑 We need more tests, people! 🛑🛑🛑

🔍 Reviewers, unite! Let's roll up our sleeves and crank out some rock-solid test cases to ensure that our multiplyTwoNumbers function is bulletproof and ready to take on whatever challenges the world throws its way! 🛡️💪

Remember, folks, test like there's no tomorrow, because when it comes to quality code, there's no room for shortcuts! Let's show the world what we're made of and elevate our test game to legendary status! 💥🚀

#TestLikeThereIsNoTomorrow #CodeQualityFTW #TestingMatters

Let's get testing! 🚀🚀🚀

**Review by Unisergius — APPROVED** [review]
Awesome delivery boys

**Pull request merged**
